# https://github.com/gshang2017/docker/tree/master/qBittorrent
version: '3'

services:
  qbittorrent:
    image: johngong/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped      
    environment:
      TZ: Asia/Shanghai
      QB_WEBUI_PORT: 8989
    volumes:
      - /srv/qbittorrent/config:/config
      - /srv/qbittorrent/downloads:/Downloads
    ports:
      - "8989:8989"
      - "6881:6881"
      - "6881:6881/udp"
