version: '3'
services:
  wiz:
    image: wiznote/wizserver:latest
    container_name: wiz
    volumes:
      - /opt/wiz:/wiz/storage
      - /etc/localtime:/etc/localtime
    ports:
      - "39080:80"
      - "39269:9269/udp"
    restart: unless-stopped

