# https://www.wiz.cn/docker.html
version: '3'

volumes:
  data:

services:
  wiz:
    image: wiznote/wizserver:latest
    container_name: wiz
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - data:/wiz/storage
    ports:
      - 80:80
      - 9269:9269/tcp
      - 9269:9269/udp

