# https://github.com/jetsung/docker-git
version: '3'

services:
  git:
    image: devcto/git:latest
    container_name: git
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      GIT_USER: ${GIT_USER}
      GIT_EMAIL: ${GIT_EMAIL}
    volumes:
      - ./init.sh:/app/init.sh
      - ./.ssh:/root/.ssh
      - /work_code:/srv
    command: -D
    