version: '3'
services:
  git:
    image: devcto/git:latest
    container_name: git-alpine
    volumes:
      - ./init.sh:/app/init.sh
      - ./.ssh:/root/.ssh
      - /work_code:/srv
    restart: unless-stopped
    command: -D
    