# https://github.com/laurent22/joplin/tree/dev/packages/server
version: '3'

networks:
  db:
    name: db
    external: true

services:
    joplin:
        image: joplin/server:latest
        container_name: joplin
        depends_on:
            - postgres
        ports:
            - "39001:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=${APP_PORT}
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=postgres
        networks:
            db: