# https://github.com/whyour/qinglong
version: '3'
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/ql/data
    ports:
      - 5700:5700


    
