version: '3'
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    hostname: qinglong
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_TG_BOT=true
      - ENABLE_WEB_PANEL=true
      - TZ=CST-8
    volumes:
        - ./data/config:/ql/config
        - ./data/db:/ql/db 
        - ./data/log:/ql/log 
        - ./data/repo:/ql/repo 
        - ./data/raw:/ql/raw 
        - ./data/scripts:/ql/scripts 
        - ./data/jbot:/ql/jbot             
    ports:
      - 5700:5700
    restart: unless-stopped


    
