# https://github.com/dani-garcia/vaultwarden
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped      
    environment:
      - TZ=Asia/Shanghai
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - ./data:/data
    ports:
      - 39081:80
