# https://github.com/dani-garcia/vaultwarden
version: '3'

volumes:
  data:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped      
    environment:
      - TZ=Asia/Shanghai
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - SMTP_HOST=<smtp.domain.tld> \
      - SMTP_FROM=<vaultwarden@domain.tld> \
      - SMTP_PORT=587 \
      - SMTP_SSL=true \
      - SMTP_USERNAME=<username> \
      - SMTP_PASSWORD=<password>
    volumes:
      - data:/data
    ports:
      - 80:80

