version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - TZ=CST-8
    volumes:
      - ./data:/data
    ports:
      - 39081:80
    restart: unless-stopped      
