version: '3'

services:
  server:
    image: quay.io/minio/minio:RELEASE.2022-03-08T22-28-51Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_SITE_NAME: "Jetsung's OSS"
      MINIO_SITE_REGION: eu-bg-1
      MINIO_SITE_COMMENT: AlphaVPS-BG
      MINIO_REGION_NAME: eu
      # MINIO_ACCESS_KEY: ACCESS_KEY
      # MINIO_SECRET_KEY: SECRET_KEY
      #MINIO_ROOT_USER: minioadmin
      #MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: https://console.oss.mydomain.com
      MINIO_SERVER_URL: https://oss.mydomain.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  data: