# https://github.com/boypt/simple-torrent

version: '3'
services:
  cloud-torrent:
    image: boypt/cloud-torrent:latest
    container_name: cloud-torrent
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      AUTH: "username:password"
      TITLE: "MySimpleTorrent"
    volumes:
      - './downloads:/downloads'
      - './torrents:/torrents'
    ports:
      - '3000:3000'