# https://github.com/boypt/simple-torrent

version: '3'
services:
  cloud-torrent:
    image: boypt/cloud-torrent
    container_name: cloud-torrent
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - './downloads:/downloads'
      - './torrents:/torrents'
    ports:
      - '3000:3000'