# https://github.com/jetsung/docker-frp
version: '3'

services:
  frpc:
    image: devcto/frpc:latest
    container_name: frpc
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./frpc.ini:/app/frpc.ini"
    network_mode: "host"
