# https://github.com/TimWolla/docker-adminer
version: '3'

networks:
  db:
    name: db
    external: true

services:

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080
    networks:
      - db
      
