version: '3'
services:
  xunsearch:
    image: docker.io/hightman/xunsearch:latest
    container_name: xunsearch
    environment:
      - TZ=CST-8
    volumes:
      - ./data:/usr/local/xunsearch/data
    ports:
      - 18383:8383 
      - 18384:8384
    restart: unless-stopped
