## 配合 adminer 使用
version: '3'

volumes:
  data:

networks:
  db:
    name: db
    external: true
    
services:
  mysql:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - db

