version: "3"
services:
  acme:
    image: neilpang/acme.sh
    container_name: acme.sh
    volumes:
      - ./out:/acme.sh
      - ./ssl:/data/ssl
    environment:
      - Ali_Key=${Ali_Key}
      - Ali_Secret=${Ali_Secret}
    network_mode: "host"
    restart: unless-stopped
    command: ["daemon"]

