version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8080:8080
      
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      PMA_ARBITRARY: 1
    ports:
      - 80:80

