# https://hub.docker.com/r/tickstep/aliyunpan-webdav
version: '3'
services:
  webdav:
    image: tickstep/aliyunpan-webdav:v0.1.3
    container_name: aliyunpan-webdav
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      # refresh token用于登录
      - ALIYUNPAN_REFRESH_TOKEN=${ALIYUNPAN_REFRESH_TOKEN}
      # webdav 登录用户名
      - ALIYUNPAN_AUTH_USER=${ALIYUNPAN_AUTH_USER}
      # webdav 登录密码
      - ALIYUNPAN_AUTH_PASSWORD=${ALIYUNPAN_AUTH_PASSWORD}
      # 指定网盘文件夹作为webdav服务根目录
      - ALIYUNPAN_PAN_DIR=/webdav/
      # 上传下载链接类型：1-默认 2-阿里ECS环境(ECS必须是经典网络类型)
      - ALIYUNPAN_TRANSFER_URL_TYPE=1
      # 上传数据块大小，单位为KB，默认为1024KB，建议范围1024KB~10240KB
      - ALIYUNPAN_BLOCK_SIZE=10240
    ports:
      - 23077:23077