# https://github.com/syncthing/syncthing/blob/main/README-Docker.md
version: "3"

volumes:
  data:

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - data:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000

